In [ ]:
#Problem1(Array Creation)
import numpy as np
#1
empty_array = np.empty((2,2))
print(empty_array)

#2
ones_array = np.ones((4,2))
print(ones_array)

#3
array_fill = np.full((3,4),7)
print(array_fill)

#4
given_array = np.array([[1,2,3],[4,5,6]])
array_zeros = np.zeros_like(given_array)
print(array_zeros)

#5
given_array = np.array([[1,2,3],[4,5,6]])
array_ones = np.ones_like(given_array)
print(array_ones)

#6
new_list = [1,2,3,4,5]
array_from_list = np.array(new_list)
print(array_from_list)


[[4.80060710e-310 0.00000000e+000]
 [6.62957679e-310 6.62957675e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Problem2(Array Manipulation)
import numpy as np

#1
array = np.arange(10,50)
print(array)

#2
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

#3
identity_matrix = np.eye(3)
print(identity_matrix)

#4
random_array = np.random.random(30)
mean_value = np.mean(random_array)
print(mean_value)

#5
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print(random_array)
print( min_value)
print( max_value)

#6
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

#7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

#8
size = 5
array = np.zeros((size, size),dtype=int)
array[0,:] = 1
array[-1,:] = 1
array[:,0] = 1
array[:,-1] = 1
print(array)

#9
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Problem3(Array Operations)
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1
add_result = x + y
print(add_result)

#2
sub_result = x - y
print(sub_result)

#3
mul_result = x * y
print(mul_result)

#4
square_result = np.square(x)
print(square_result)

#5
dot_V_W = np.dot(v, w)
print(dot_V_W)
dot_X_V = np.dot(x, v)
print(dot_X_V)
dot_X_Y = np.dot(x, y)
print(dot_X_Y)

#6
concat_x_y = np.concatenate((x, y), axis=0)
print(concat_x_y)
concat_v_w = np.concatenate((v, w), axis=0)
print(concat_v_w)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [ ]:
#7
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
conca = np.concatenate((x,v), axis=0)
print(conca)
#Error Explanation: All the input arrays must have same number of dimensions.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [4]:
#Problem 4(Matrix Operations)

import numpy as np

# Part 1: Inverse of A
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)
print()

I = np.dot(A_inverse, A)
print("I = \n", I)
print("Hence A*A⁻¹ = I, proved")
print()

# Part 2: Matrix Multiplication
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print()
print("BA = \n", BA)
print()

# Part 3: Transpose Property
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("(AB)ᵀ = \n", AB_T)
print()
print("Bᵀ * Aᵀ = \n", B_T_A_T)
print()

# Part 4: Cramer's Rule
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([[-1], [-3], [9]])

# Calculate determinant of A
det_A = np.linalg.det(A)
print(f"det(A) = {det_A}")
print()

# Create matrices A_x, A_y, and A_z by replacing columns of A with B
A_x = A.copy()
A_x[:, 0] = B[:, 0]

A_y = A.copy()
A_y[:, 1] = B[:, 0]

A_z = A.copy()
A_z[:, 2] = B[:, 0]

# Calculate the determinants of A_x, A_y, and A_z
det_A_x = np.linalg.det(A_x)
det_A_y = np.linalg.det(A_y)
det_A_z = np.linalg.det(A_z)

# Calculate the solutions for x, y, z using Cramer's Rule
x = det_A_x / det_A
y = det_A_y / det_A
z = det_A_z / det_A

print(f"Solution using Cramer's Rule:\nx = {x}\ny = {y}\nz = {z}")
print()

# Part 5: Solve using Inverse Method
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution for [x, y, z] using inverse method:\n", X)


Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

I = 
 [[1.00000000e+00 0.00000000e+00]
 [5.55111512e-16 1.00000000e+00]]
Hence A*A⁻¹ = I, proved

AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

(AB)ᵀ = 
 [[23 51]
 [13 29]]

Bᵀ * Aᵀ = 
 [[23 51]
 [13 29]]

det(A) = -19.000000000000004

Solution using Cramer's Rule:
x = 2.0000000000000004
y = 1.0
z = -1.9999999999999993

Solution for [x, y, z] using inverse method:
 [[ 2.]
 [ 1.]
 [-2.]]
